### ISSUE TITLE
Doesn't work with AWS configs

### ISSUE THREAD

**Issue by kkolk** [tmont/tail-stack-events#4]
I have a [~/.aws/config file](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html) setup with various profiles [to assume different roles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html).   It's setup this way because I login into an organizational AWS account then assume roles in it's child accounts.

This utility unfortunately seems unaware of this functionality and throws this error:

```
message: 'Missing credentials in config',
  code: 'CredentialsError',
```

**Comment by tmont** [comment]
This was fixed in v2.0.0 (bd3ce90).
