### ISSUE TITLE
won't install -- requires a peer of aws-sdk@2.x but none was installed

### ISSUE THREAD

**Issue by alexnauda** [tmont/tail-stack-events#5]
$ npm install -g tail-stack-events
/usr/local/bin/tail-stack-events -> /usr/local/lib/node_modules/tail-stack-events/tail-stack-events.js
npm WARN tail-stack-events@1.2.0 requires a peer of aws-sdk@2.x but none was installed.

+ tail-stack-events@1.2.0
added 1 package in 4.62s

**Comment by tmont** [comment]
That's by design, you'll have to install the `aws-sdk` package yourself, e.g.

```
npm install -g aws-sdk
```
